apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
      tier: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rhorv/rabbitmq:latest
        ports:
        - containerPort: 15672
        - containerPort: 5672
        - containerPort: 5671

