apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq-service
    tier: rabbitmq
spec:
  ports:
  - name: management-ui
    port: 15672
    targetPort: 15672
  - name: queue-traffic
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
    tier: rabbitmq
  clusterIP: 10.96.1.1
