apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq-service
    tier: rabbitmq
spec:
  ports:
  - port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
    tier: rabbitmq
  clusterIP: 10.0.4.1
