apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: default
  labels:
    k8s-app: logstash
data:
data:
  logstash.conf: |-
    input {
      beats {
        port => 5044
        type => "container_logs"
      }
    }
    output {
      if [type] == "business_events" {
        elasticsearch {
          hosts => ["https://vpc-wp-poc-elk-elastic-ehb5fgovdzixbkmo2yuulvlnae.eu-west-2.es.amazonaws.com:443"]
          index => "businessevents-%{+YYYY.MM}"
          manage_template => false
          ilm_enabled => false
        }
      } else {
        elasticsearch {
          hosts => ["https://vpc-wp-poc-elk-elastic-ehb5fgovdzixbkmo2yuulvlnae.eu-west-2.es.amazonaws.com:443"]
          index => "%{[@metadata][beat]}-%{+YYYY.MM}"
          manage_template => false
          ilm_enabled => false
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  selector:
    app: logstash
  ports:
  - name: beats
    port: 5044
    targetPort: 5044
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  selector:
    matchLabels:
      app: logstash
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash-oss:7.10.2
        ports:
        - containerPort: 5044
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          readOnly: true
          subPath: logstash.conf
      volumes:
      - name: config
        configMap:
          defaultMode: 0640
          name: logstash-config
