apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq-server
  ports:
  - name: management-ui
    port: 15672
    targetPort: 15672
  - name: queue-traffic
    port: 5672
    targetPort: 5672
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-server
spec:
  selector:
    matchLabels:
      app: rabbitmq-server
  replicas: 1
  serviceName: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq-server
    spec:
      containers:
      - name: rabbitmq
        image: rhorv/rabbitmq:latest
        ports:
        - containerPort: 15672
        - containerPort: 5672
        - containerPort: 5671
        env:
        - name: RABBITMQ_NODENAME
          value: rabbitmq-server@localhost
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: admin_username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: admin_password
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
